# POST error response
# name - required, min length 5, max length 100
# category - required, must be one of the following: Backend|Frontend|Fullstack

POST http://localhost:8080/api/courses
Content-Type: application/json

{
  "name": "1",
  "category": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

###

# POST success response

POST http://localhost:8080/api/courses
Content-Type: application/json

{
  "name": "Vue.js",
  "category": "Frontend"
}

###

# GET all courses

GET http://localhost:8080/api/courses
Content-Type: application/json

###

# GET course by id

GET http://localhost:8080/api/courses/2
Content-Type: application/json

###

# DELETE course by id

DELETE http://localhost:8080/api/courses/2
Content-Type: application/json

###
